Create pull_request_template.md
project-march/.github pull request #4
Opened 2019-09-23 14:45 UTC by Olavhaasie

Added pull request template.

2019-09-23 15:50 UTC, Roelemans commented on PULL_REQUEST_TEMPLATE/pull_request_template.md
> +## Issues
There should only be one issue

2019-09-23 15:56 UTC, Roelemans requested changes

2019-09-23 15:56 UTC, Roelemans commented on PULL_REQUEST_TEMPLATE/pull_request_template.md
> +e.g. closes PM-34
I would turn this around - move "Close PM-" out of the comments and put in on top, remove ##Issues and add a small comment description (e.g. "
<!--
Reference keyword to Jira issue
-->
")

2019-09-24 08:20 UTC, RutgerVanBeek approved these changes

2019-09-24 09:15 UTC, Roelemans approved these changes
Ziek mooi

2019-09-24 09:15 UTC, merged